name: 'kafka'
version: 0.1.0
description: Kafka Client library for Dartlang
homepage: https://github.com/pulyaevskiy/dart-kafka
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  logging: "^0.11.1+1"

dev_dependencies:
  test: "^0.12.4+7"
  mockito: "^0.11.0"
  dart_coveralls: "^0.4.0"
